esphome:
  name: esphome-dualreed
  friendly_name: esphome-dualreed

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QVrqwmSYH8d30x4hgAqlM5Uzr17m6dDwmoLchhNBpHQ="

ota:
  password: "880a98cad5ef1e07222f8895b570ee93"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Dualreed"
    password: "cRd74MEKt8jR"

binary_sensor:
  - platform: gpio
    pin:
      id: R1
      number: 5
      mode:
        input: true
        pullup: true
    name: "reedswitch01"
    device_class: door
  - platform: gpio
    pin:
      id: R2
      number: 16
      mode:
        input: true
        pullup: true
    name: "reedswitch02"
    device_class: door    

sensor:
  - platform: template
    name: "Reed puzzle Solved"
    unit_of_measurement: "%"
    update_interval: 2s
    lambda: |-
      if (!digitalRead(5) && !digitalRead(16)) {
        return 100; 
      }
      else if (!digitalRead(5)) {
        return 50; 
      }
      else if (!digitalRead(16)) {
        return 50; 
      }
      else {
        return 0;
      }
      
captive_portal:
    